services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.production
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod    # Dockerfile dedicato alla build
      args:
        - VITE_API_URL=http://localhost:3000
    container_name: frontend
    ports:
      - "80:80"                      # Nginx serve sulla 80
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge